spring:
  datasource:
    url: ${DB_URL:jdbc:postgresql://localhost:5432/gestion_stock}
    username: ${DB_USERNAME:gestion_stock}
    password: ${DB_PASSWORD:gestion_stock}
    driver-class-name: org.postgresql.Driver

  jpa:
    hibernate:
      ddl-auto: validate
    open-in-view: false
    show-sql: false
    properties:
      hibernate:
        format_sql: true
        dialect: org.hibernate.dialect.PostgreSQLDialect

server:
  port: ${SERVER_PORT:8081}

jwt:
  secret: ${JWT_SECRET:dev_secret_key_just_for_local_tests_32chars_min}
