create table admin_notifications (
    id bigint generated by default as identity primary key,
    organisation_id bigint not null,
    type varchar(60) not null,
    severity varchar(20) not null,
    title varchar(180) not null,
    message varchar(600) not null,
    purchase_order_id bigint,
    deduplication_key varchar(180) not null,
    read_at timestamp,
    created_at timestamp not null,
    constraint fk_admin_notifications_organisation
        foreign key (organisation_id) references organisations(id),
    constraint fk_admin_notifications_purchase_order
        foreign key (purchase_order_id) references purchase_orders(id),
    constraint uk_admin_notifications_dedup unique (organisation_id, deduplication_key)
);

create index idx_admin_notifications_org_read_created
    on admin_notifications (organisation_id, read_at, created_at);
