alter table admin_notifications
    add column supplier_id bigint;

alter table admin_notifications
    add constraint fk_admin_notifications_supplier
        foreign key (supplier_id) references suppliers(id);

create table admin_notification_preferences (
    id bigint generated by default as identity primary key,
    organisation_id bigint not null,
    threshold_notifications_enabled boolean not null default true,
    critical_stockout_notifications_enabled boolean not null default true,
    updated_at timestamp not null,
    updated_by_user_id bigint,
    constraint fk_admin_notification_preferences_organisation
        foreign key (organisation_id) references organisations(id),
    constraint uk_admin_notification_preferences_org unique (organisation_id)
);
