create table admin_notification_actions (
    id bigint generated by default as identity primary key,
    notification_id bigint not null,
    organisation_id bigint not null,
    action_code varchar(60) not null,
    reason varchar(600),
    actor_user_id bigint not null,
    created_at timestamp not null,
    constraint fk_admin_notification_actions_notification
        foreign key (notification_id) references admin_notifications(id)
);

create index idx_admin_notification_actions_notification_created
    on admin_notification_actions (notification_id, created_at);
