create table sales (
    id bigint generated by default as identity primary key,
    organisation_id bigint not null,
    reference varchar(64) not null,
    customer_name varchar(160),
    channel varchar(30) not null,
    status varchar(30) not null,
    total_amount numeric(12, 2) not null,
    sold_at timestamp not null,
    created_at timestamp not null,
    constraint fk_sales_organisation foreign key (organisation_id) references organisations (id),
    constraint uk_sales_reference_organisation unique (reference, organisation_id),
    constraint ck_sales_total_amount check (total_amount >= 0),
    constraint ck_sales_channel check (channel in ('STORE', 'WEB', 'PHONE', 'B2B', 'OTHER')),
    constraint ck_sales_status check (status in ('COMPLETED', 'CANCELLED'))
);

create table sale_lines (
    id bigint generated by default as identity primary key,
    sale_id bigint not null,
    organisation_id bigint not null,
    product_id bigint not null,
    quantity integer not null,
    unit_price numeric(12, 2) not null,
    line_total numeric(12, 2) not null,
    constraint fk_sale_lines_sale foreign key (sale_id) references sales (id),
    constraint fk_sale_lines_organisation foreign key (organisation_id) references organisations (id),
    constraint fk_sale_lines_product foreign key (product_id) references products (id),
    constraint ck_sale_lines_quantity check (quantity > 0),
    constraint ck_sale_lines_unit_price check (unit_price >= 0),
    constraint ck_sale_lines_total check (line_total >= 0)
);

create index idx_sales_organisation_sold_at on sales (organisation_id, sold_at desc);
create index idx_sale_lines_organisation_product on sale_lines (organisation_id, product_id);
