create table ai_forecast_snapshots (
    id bigint generated by default as identity primary key,
    organisation_id bigint not null,
    product_id bigint not null,
    horizon_days integer not null,
    target_date date not null,
    predicted_quantity numeric(12, 2) not null,
    confidence_score numeric(5, 2) not null,
    model_name varchar(80) not null,
    generated_at timestamp not null,
    constraint fk_ai_forecast_snapshots_organisation foreign key (organisation_id) references organisations (id) on delete cascade,
    constraint fk_ai_forecast_snapshots_product foreign key (product_id) references products (id) on delete cascade,
    constraint ck_ai_forecast_snapshots_horizon check (horizon_days in (7, 30, 90)),
    constraint ck_ai_forecast_snapshots_quantity check (predicted_quantity >= 0)
);

create index idx_ai_forecast_snapshots_org_product on ai_forecast_snapshots (organisation_id, product_id, horizon_days, generated_at desc);
create index idx_ai_forecast_snapshots_org_target on ai_forecast_snapshots (organisation_id, target_date desc);
