create table organisations (
    id bigint generated by default as identity primary key,
    name varchar(120) not null,
    constraint uk_organisations_name unique (name)
);

create table users (
    id bigint generated by default as identity primary key,
    email varchar(180) not null,
    password varchar(255) not null,
    organisation_id bigint not null,
    role varchar(20) not null,
    constraint uk_users_email unique (email),
    constraint fk_users_organisation foreign key (organisation_id) references organisations (id),
    constraint ck_users_role check (role in ('ADMIN', 'USER'))
);

create table products (
    id bigint generated by default as identity primary key,
    organisation_id bigint not null,
    name varchar(120) not null,
    sku varchar(64) not null,
    category varchar(120),
    min_stock integer not null,
    unit varchar(32),
    constraint fk_products_organisation foreign key (organisation_id) references organisations (id),
    constraint uk_products_sku_organisation unique (sku, organisation_id),
    constraint ck_products_min_stock check (min_stock >= 0)
);

create table stocks (
    id bigint generated by default as identity primary key,
    organisation_id bigint not null,
    product_id bigint not null,
    quantity integer not null,
    constraint fk_stocks_organisation foreign key (organisation_id) references organisations (id),
    constraint fk_stocks_product foreign key (product_id) references products (id),
    constraint uk_stocks_product_organisation unique (product_id, organisation_id),
    constraint ck_stocks_quantity check (quantity >= 0)
);

create table stock_movements (
    id bigint generated by default as identity primary key,
    organisation_id bigint not null,
    product_id bigint not null,
    quantity integer not null,
    type varchar(20) not null,
    created_at timestamp not null,
    constraint fk_stock_movements_organisation foreign key (organisation_id) references organisations (id),
    constraint fk_stock_movements_product foreign key (product_id) references products (id),
    constraint ck_stock_movements_quantity check (quantity > 0),
    constraint ck_stock_movements_type check (type in ('IN', 'OUT', 'ADJUST'))
);

create index idx_products_organisation on products (organisation_id);
create index idx_stocks_organisation on stocks (organisation_id);
create index idx_stock_movements_organisation_created_at on stock_movements (organisation_id, created_at desc);
create index idx_stock_movements_product_created_at on stock_movements (organisation_id, product_id, created_at desc);
