alter table users drop constraint ck_users_role;

alter table users
    add constraint ck_users_role check (role in ('OWNER', 'ADMIN', 'USER'));

alter table organisations add column created_at timestamp not null default current_timestamp;
alter table organisations add column status varchar(20) not null default 'ACTIVE';

alter table organisations
    add constraint ck_organisations_status check (status in ('ACTIVE', 'SUSPENDED', 'TRIAL'));

create table legal_settings (
    id bigint generated by default as identity primary key,
    company_name varchar(160) not null,
    legal_notice text,
    privacy_policy text,
    terms text,
    legal_document_url varchar(500),
    privacy_document_url varchar(500),
    terms_document_url varchar(500),
    updated_at timestamp not null,
    updated_by_user_id bigint,
    constraint fk_legal_settings_updated_by
        foreign key (updated_by_user_id) references users(id)
);
