ALTER TABLE users ADD COLUMN IF NOT EXISTS enabled BOOLEAN NOT NULL DEFAULT TRUE;
ALTER TABLE users ADD COLUMN IF NOT EXISTS last_login_at TIMESTAMP;

ALTER TABLE organisations ADD COLUMN IF NOT EXISTS logo_url VARCHAR(500);
ALTER TABLE organisations ADD COLUMN IF NOT EXISTS tax_id VARCHAR(80);
ALTER TABLE organisations ADD COLUMN IF NOT EXISTS website VARCHAR(220);
ALTER TABLE organisations ADD COLUMN IF NOT EXISTS stock_alert_email VARCHAR(180);
ALTER TABLE organisations ADD COLUMN IF NOT EXISTS default_lead_time_days INT NOT NULL DEFAULT 7;
