create table billing_subscriptions (
    id bigint generated by default as identity primary key,
    organisation_id bigint not null,
    plan_code varchar(50) not null,
    status varchar(30) not null,
    stripe_customer_id varchar(255),
    stripe_subscription_id varchar(255),
    current_period_end timestamp,
    trial_ends_at timestamp,
    cancel_at_period_end boolean not null default false,
    created_at timestamp not null,
    updated_at timestamp not null,
    constraint fk_billing_subscriptions_organisation
        foreign key (organisation_id) references organisations(id),
    constraint uk_billing_subscriptions_organisation unique (organisation_id)
);

create unique index uk_billing_subscriptions_stripe_customer
    on billing_subscriptions(stripe_customer_id);

create unique index uk_billing_subscriptions_stripe_subscription
    on billing_subscriptions(stripe_subscription_id);
