ALTER TABLE support_messages
    ADD COLUMN attachment_name VARCHAR(220);

ALTER TABLE support_messages
    ADD COLUMN attachment_content_type VARCHAR(120);

ALTER TABLE support_messages
    ADD COLUMN attachment_data TEXT;

CREATE TABLE support_replies (
    id BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    support_message_id BIGINT NOT NULL REFERENCES support_messages(id) ON DELETE CASCADE,
    author_user_id BIGINT REFERENCES users(id) ON DELETE SET NULL,
    author_email VARCHAR(180) NOT NULL,
    author_role VARCHAR(20) NOT NULL,
    message TEXT NOT NULL,
    attachment_name VARCHAR(220),
    attachment_content_type VARCHAR(120),
    attachment_data TEXT,
    created_at TIMESTAMP NOT NULL DEFAULT CURRENT_TIMESTAMP
);

CREATE INDEX idx_support_replies_message ON support_replies(support_message_id, created_at ASC);
