create table ai_forecasts (
    id bigint generated by default as identity primary key,
    organisation_id bigint not null,
    product_id bigint not null,
    horizon_days integer not null,
    predicted_quantity numeric(12, 2) not null,
    confidence_score numeric(5, 2) not null,
    model_name varchar(80) not null,
    generated_at timestamp not null,
    constraint fk_ai_forecasts_organisation foreign key (organisation_id) references organisations (id),
    constraint fk_ai_forecasts_product foreign key (product_id) references products (id),
    constraint ck_ai_forecasts_horizon check (horizon_days in (7, 30, 90)),
    constraint ck_ai_forecasts_predicted_quantity check (predicted_quantity >= 0)
);

create table ai_stockout_risks (
    id bigint generated by default as identity primary key,
    organisation_id bigint not null,
    product_id bigint not null,
    estimated_stockout_date date,
    risk_score numeric(5, 2) not null,
    risk_level varchar(20) not null,
    reason text,
    generated_at timestamp not null,
    constraint fk_ai_stockout_risks_organisation foreign key (organisation_id) references organisations (id),
    constraint fk_ai_stockout_risks_product foreign key (product_id) references products (id),
    constraint ck_ai_stockout_risks_level check (risk_level in ('LOW', 'MEDIUM', 'HIGH'))
);

create table ai_reorder_recommendations (
    id bigint generated by default as identity primary key,
    organisation_id bigint not null,
    product_id bigint not null,
    recommended_quantity integer not null,
    lead_time_days integer not null,
    safety_stock integer not null,
    reason text,
    status varchar(20) not null default 'PENDING',
    generated_at timestamp not null,
    constraint fk_ai_reorder_recommendations_organisation foreign key (organisation_id) references organisations (id),
    constraint fk_ai_reorder_recommendations_product foreign key (product_id) references products (id),
    constraint ck_ai_reorder_recommendations_quantity check (recommended_quantity >= 0),
    constraint ck_ai_reorder_recommendations_status check (status in ('PENDING', 'APPROVED', 'REJECTED'))
);

create table ai_anomalies (
    id bigint generated by default as identity primary key,
    organisation_id bigint not null,
    product_id bigint,
    stock_movement_id bigint,
    anomaly_type varchar(40) not null,
    severity varchar(20) not null,
    score numeric(5, 2) not null,
    explanation text,
    detected_at timestamp not null,
    constraint fk_ai_anomalies_organisation foreign key (organisation_id) references organisations (id),
    constraint fk_ai_anomalies_product foreign key (product_id) references products (id),
    constraint fk_ai_anomalies_movement foreign key (stock_movement_id) references stock_movements (id),
    constraint ck_ai_anomalies_severity check (severity in ('LOW', 'MEDIUM', 'HIGH'))
);

create table ai_insights (
    id bigint generated by default as identity primary key,
    organisation_id bigint not null,
    title varchar(160) not null,
    content text not null,
    insight_type varchar(40) not null,
    priority varchar(20) not null,
    generated_at timestamp not null,
    constraint fk_ai_insights_organisation foreign key (organisation_id) references organisations (id),
    constraint ck_ai_insights_priority check (priority in ('LOW', 'MEDIUM', 'HIGH'))
);

create table ai_audit_logs (
    id bigint generated by default as identity primary key,
    organisation_id bigint not null,
    user_id bigint,
    action varchar(80) not null,
    resource_type varchar(80),
    resource_id bigint,
    metadata text,
    created_at timestamp not null,
    constraint fk_ai_audit_logs_organisation foreign key (organisation_id) references organisations (id),
    constraint fk_ai_audit_logs_user foreign key (user_id) references users (id)
);

create index idx_ai_forecasts_org_product on ai_forecasts (organisation_id, product_id, horizon_days);
create index idx_ai_stockout_risks_org_score on ai_stockout_risks (organisation_id, risk_score desc);
create index idx_ai_reorder_recommendations_org_status on ai_reorder_recommendations (organisation_id, status);
create index idx_ai_anomalies_org_detected_at on ai_anomalies (organisation_id, detected_at desc);
create index idx_ai_insights_org_generated_at on ai_insights (organisation_id, generated_at desc);
create index idx_ai_audit_logs_org_created_at on ai_audit_logs (organisation_id, created_at desc);
