create table ai_runs (
    id bigint generated by default as identity primary key,
    organisation_id bigint not null,
    requested_by_user_id bigint,
    status varchar(20) not null,
    trigger_type varchar(30) not null,
    started_at timestamp not null,
    completed_at timestamp,
    error_message text,
    forecasts_count integer not null default 0,
    risks_count integer not null default 0,
    recommendations_count integer not null default 0,
    anomalies_count integer not null default 0,
    insights_count integer not null default 0,
    model_source varchar(40) not null default 'LOCAL_FALLBACK',
    constraint fk_ai_runs_organisation foreign key (organisation_id) references organisations (id),
    constraint fk_ai_runs_requested_by foreign key (requested_by_user_id) references users (id),
    constraint ck_ai_runs_status check (status in ('QUEUED', 'RUNNING', 'SUCCEEDED', 'FAILED')),
    constraint ck_ai_runs_trigger_type check (trigger_type in ('MANUAL', 'SCHEDULED', 'INITIAL')),
    constraint ck_ai_runs_model_source check (model_source in ('FASTAPI', 'LOCAL_FALLBACK'))
);

create index idx_ai_runs_org_started_at on ai_runs (organisation_id, started_at desc);
create index idx_ai_runs_org_status on ai_runs (organisation_id, status);
