create table suppliers (
    id bigint generated by default as identity primary key,
    organisation_id bigint not null,
    name varchar(160) not null,
    email varchar(180),
    phone varchar(60),
    lead_time_days integer not null default 7,
    active boolean not null default true,
    created_at timestamp not null,
    constraint fk_suppliers_organisation foreign key (organisation_id) references organisations (id),
    constraint uk_suppliers_org_name unique (organisation_id, name),
    constraint ck_suppliers_lead_time check (lead_time_days >= 0)
);

create table purchase_orders (
    id bigint generated by default as identity primary key,
    organisation_id bigint not null,
    supplier_id bigint not null,
    status varchar(20) not null,
    expected_delivery_date date,
    created_at timestamp not null,
    received_at timestamp,
    constraint fk_purchase_orders_organisation foreign key (organisation_id) references organisations (id),
    constraint fk_purchase_orders_supplier foreign key (supplier_id) references suppliers (id),
    constraint ck_purchase_orders_status check (status in ('DRAFT', 'ORDERED', 'RECEIVED', 'CANCELLED'))
);

create table purchase_order_lines (
    id bigint generated by default as identity primary key,
    purchase_order_id bigint not null,
    product_id bigint not null,
    quantity integer not null,
    unit_cost numeric(12, 2),
    constraint fk_purchase_order_lines_order foreign key (purchase_order_id) references purchase_orders (id),
    constraint fk_purchase_order_lines_product foreign key (product_id) references products (id),
    constraint ck_purchase_order_lines_quantity check (quantity > 0),
    constraint ck_purchase_order_lines_unit_cost check (unit_cost is null or unit_cost >= 0)
);

create index idx_suppliers_org on suppliers (organisation_id, active);
create index idx_purchase_orders_org_status on purchase_orders (organisation_id, status);
create index idx_purchase_order_lines_order on purchase_order_lines (purchase_order_id);
