create table product_suppliers (
    id bigint generated by default as identity primary key,
    organisation_id bigint not null,
    product_id bigint not null,
    supplier_id bigint not null,
    unit_cost numeric(12, 2),
    minimum_order_quantity integer not null default 1,
    preferred boolean not null default false,
    active boolean not null default true,
    created_at timestamp not null,
    constraint fk_product_suppliers_organisation foreign key (organisation_id) references organisations (id),
    constraint fk_product_suppliers_product foreign key (product_id) references products (id),
    constraint fk_product_suppliers_supplier foreign key (supplier_id) references suppliers (id),
    constraint uk_product_suppliers_product_supplier unique (organisation_id, product_id, supplier_id),
    constraint ck_product_suppliers_unit_cost check (unit_cost is null or unit_cost >= 0),
    constraint ck_product_suppliers_minimum_order_quantity check (minimum_order_quantity > 0)
);

create index idx_product_suppliers_product
    on product_suppliers (organisation_id, product_id, active);
