create table purchase_order_audit_logs (
    id bigint generated by default as identity primary key,
    organisation_id bigint not null,
    purchase_order_id bigint not null,
    action varchar(40) not null,
    previous_status varchar(20),
    new_status varchar(20) not null,
    actor_user_id bigint,
    actor_email varchar(180) not null,
    actor_role varchar(20) not null,
    order_total numeric(19, 2) not null,
    created_at timestamp not null,
    constraint fk_purchase_order_audit_order
        foreign key (purchase_order_id) references purchase_orders(id)
);

create index idx_purchase_order_audit_org_order
    on purchase_order_audit_logs (organisation_id, purchase_order_id, created_at);
