create table procurement_approval_settings (
    id bigint generated by default as identity primary key,
    organisation_id bigint not null,
    approval_threshold numeric(19, 2) not null,
    updated_at timestamp not null,
    updated_by_user_id bigint,
    constraint fk_procurement_approval_settings_organisation
        foreign key (organisation_id) references organisations(id),
    constraint uk_procurement_approval_settings_org unique (organisation_id),
    constraint ck_procurement_approval_threshold check (approval_threshold >= 0)
);
